### ISSUE TITLE
STACK Layout - list order inverted

### ISSUE THREAD

**Issue by LampadinoMania** [TheAnkurPanchani/card_swiper#30]
Good morning, 

I am having a problem using STACK Layout with a list: it seems that the order of the elemets is inverted during elements swiping.
Example (gif attached): 

1. The first element on the stack is the 2
2. The user makes the swipe in order to get the element 1 (during the movement it is possible to see that under the element 2 there is the element 1)
3. During the swipe animation, item 1 is actually displayed
4. As soon as the animation is completed the element 1 is changed with the element 3 

It seems that the animation swiping is the opposite of the list shifting order.

![wrong swiping](https://user-images.githubusercontent.com/98524995/151346968-22d80ce0-772b-4ed4-bb16-1890a745411e.gif)

Here's the code:

```
import 'package:card_swiper/card_swiper.dart';
import 'package:flutter/material.dart';


List prova = ["1", "2", "3", "4", "5", "6", "7", "8"];

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page', key: ValueKey(1),),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({required Key key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: SizedBox(
          width: 200,
          height: 200,
          child: Swiper(
            itemBuilder: (BuildContext context, int index){
              final item = prova[index];
              return SizedBox(
                width: 150,
                height: 150,
                child: Container(
                  decoration: BoxDecoration(border: Border.all(color: Colors.black)),
                  child: Text(index.toString())));
            },
            index: 0,
            axisDirection: AxisDirection.right,
            scrollDirection: Axis.horizontal,
            loop: true,
            itemCount: prova.length,
            layout: SwiperLayout.STACK,
            itemHeight: 150,
            itemWidth: 150,
            pagination: SwiperPagination(),
            // control: SwiperControl(),
          ),
        ),
      ),
    );
  }
}
```

**Comment by CharlesMangwa** [comment]
Just installed the library this morning @LampadinoMania and am facing pretty much the same issue.  The weird thing is that `onIndexChanged` does allow to print the proper `index`, but if I print it from within `itemBuilder` as well, the order doesn't make much sense indeed. I'll let you know if I can come up with something.

**Comment by CharlesMangwa** [comment]
FWIW here's a visual representation of what the issue is for me. As you can see, the (problematic) behaviour is the same as @LampadinoMania:

https://user-images.githubusercontent.com/8975443/151355117-81245454-b367-42fb-8ced-4e62f1b2c122.mov

**Comment by MiguelHL** [comment]
I had the same problem and you only have to change the version of the package, versions 2.0.0 and 2.0.1 have the same error, you should change it to 1.0.4. 
Hope this can help you @CharlesMangwa

**Comment by CharlesMangwa** [comment]
Thanks for the heads up @MiguelHL, v1.0.4 does not have the issue indeed! Unfortunately, the `axisDirection` property is not available there but I guess I can just fork the lib for now and apply https://github.com/TheAnkurPanchani/card_swiper/commit/f7a9bf655e5f4cfa434806f8907812cbbc809cbe.

**Comment by CharlesMangwa** [comment]
OK after some investigation in the internals of the lib and the previous commits, I managed to "fix" it. So, it seems like the issue is coming from:

https://github.com/TheAnkurPanchani/card_swiper/blob/7b6b68db638170ff19b30ae8fcac57082c7d275b/lib/src/custom_layout.dart#L210-L215

after this change was introduced: https://github.com/TheAnkurPanchani/card_swiper/commit/f7a9bf655e5f4cfa434806f8907812cbbc809cbe#diff-d1e5d4e270664cc2388fc8b37dd68ef5f513da1be06c5e4d008fa9565f8d2eecL208-L213

So I forked the latest version, reverted this specific change and got to this status: the 1st item is correct, but not the following ones:

https://user-images.githubusercontent.com/8975443/151563228-6ce0d15e-b4a4-411c-81f5-84eca95bd4e9.mov

From this, I made 2 changes in my own code to get it to work:
1. Reversed my `List`. 
```diff
- itemBuilder: (BuildContext context, int index) => MyWidget(item: myList.elementAt(index)),
+ itemBuilder: (BuildContext context, int index) => MyWidget(item: myList.reversed.elementAt(index)),
```

Which gets it to a valid state, minor the 1st item being off now:

https://user-images.githubusercontent.com/8975443/151563504-0deb9597-6eae-476e-816d-2b97c543a033.mov

2. Change the initial `index`
```diff
+ index: -1,
```

And voilà!


https://user-images.githubusercontent.com/8975443/151563913-c1814487-12af-49e3-85be-3badb8fffdde.mov

Hope this helps you as well @LampadinoMania!

**Comment by TheAnkurPanchani** [comment]
This is fixed in latest version. Please check and confirm. Thanks!

**Comment by CharlesMangwa** [comment]
Just installed that latest version (`2.0.3`) and this issue has been addressed on my side indeed. Thanks so much @TheAnkurPanchani!

**Comment by k-ane** [comment]
This issue is still prevalent in the latest versions, except that it happens on autoplay rather than swipe.

So when I use a STACK layout, manually swiping works fine, but the autoplay does the weird swapping mentioned above.

I had to go all the way back to 1.0.4 to get a fully working implementation.

**Comment by TheAnkurPanchani** [comment]
@k-ane : Please raise a fresh issue. I will fix it asap.
